version: "3.8"
services:
    skebap-backend:
        build: .
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASS}
        ports:
            - "8080:80"
    db:
        image: postgres
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASS}
        volumes:
            - local_pgdata:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    local_pgdata:
    pgadmin-data:
